INSERT INTO `category` (`id`,`category_name`) VALUES (0,'UNSORTED');
INSERT INTO `category` (`id`,`category_name`) VALUES (185075,'Activewear Bottoms');
INSERT INTO `category` (`id`,`category_name`) VALUES (185082,'Activewear Tops');
INSERT INTO `category` (`id`,`category_name`) VALUES (20081,'Antiques');
INSERT INTO `category` (`id`,`category_name`) VALUES (550,'Art');
INSERT INTO `category` (`id`,`category_name`) VALUES (29792,'Audiobooks');
INSERT INTO `category` (`id`,`category_name`) VALUES (2984,'Baby');
INSERT INTO `category` (`id`,`category_name`) VALUES (3082,'Baby & Toddler Clothing');
INSERT INTO `category` (`id`,`category_name`) VALUES (162045,'Batteries');
INSERT INTO `category` (`id`,`category_name`) VALUES (267,'Books');
INSERT INTO `category` (`id`,`category_name`) VALUES (37943,'Boxes');
INSERT INTO `category` (`id`,`category_name`) VALUES (12576,'Business & Industrial');
INSERT INTO `category` (`id`,`category_name`) VALUES (155707,'Cables & Adapters');
INSERT INTO `category` (`id`,`category_name`) VALUES (625,'Cameras & Photo');
INSERT INTO `category` (`id`,`category_name`) VALUES (100982,'Backpacks');
INSERT INTO `category` (`id`,`category_name`) VALUES (182183,'Cars, Trucks & Motorcycles');
INSERT INTO `category` (`id`,`category_name`) VALUES (107894,'Cases, Bags & Covers');
INSERT INTO `category` (`id`,`category_name`) VALUES (80135,'CD, DVD & Blu-ray Discs');
INSERT INTO `category` (`id`,`category_name`) VALUES (15032,'Cell Phones & Accessories');
INSERT INTO `category` (`id`,`category_name`) VALUES (106121,'Clothing & Shoe Care');
INSERT INTO `category` (`id`,`category_name`) VALUES (11116,'Coins & Paper Money');
INSERT INTO `category` (`id`,`category_name`) VALUES (1,'Collectibles');
INSERT INTO `category` (`id`,`category_name`) VALUES (58058,'Computers/Tablets & Networking');
INSERT INTO `category` (`id`,`category_name`) VALUES (293,'Consumer Electronics');
INSERT INTO `category` (`id`,`category_name`) VALUES (11104,'Cookbooks');
INSERT INTO `category` (`id`,`category_name`) VALUES (163147,'Costumes, Reenactment, Theater');
INSERT INTO `category` (`id`,`category_name`) VALUES (164,'CPUs/Processors');
INSERT INTO `category` (`id`,`category_name`) VALUES (112425,'Dancewear');
INSERT INTO `category` (`id`,`category_name`) VALUES (31388,'Digital Cameras');
INSERT INTO `category` (`id`,`category_name`) VALUES (63861,'Dresses');
INSERT INTO `category` (`id`,`category_name`) VALUES (617,'DVDs & Blu-ray Discs');
INSERT INTO `category` (`id`,`category_name`) VALUES (11232,'DVDs & Movies');
INSERT INTO `category` (`id`,`category_name`) VALUES (2540,'Electronic Games');
INSERT INTO `category` (`id`,`category_name`) VALUES (171228,'Fiction & Literature');
INSERT INTO `category` (`id`,`category_name`) VALUES (4201,'Film');
INSERT INTO `category` (`id`,`category_name`) VALUES (20104,'Flatware & Silverware');
INSERT INTO `category` (`id`,`category_name`) VALUES (4708,'Garden');
INSERT INTO `category` (`id`,`category_name`) VALUES (172008,'Gift Cards & Coupons');
INSERT INTO `category` (`id`,`category_name`) VALUES (27386,'Graphics/Video Cards');
INSERT INTO `category` (`id`,`category_name`) VALUES (26395,'Health & Beauty');
INSERT INTO `category` (`id`,`category_name`) VALUES (11700,'Home & Garden');
INSERT INTO `category` (`id`,`category_name`) VALUES (281,'Jewelry & Watches');
INSERT INTO `category` (`id`,`category_name`) VALUES (171146,'Kids Clothing, Shoes & Accs');
INSERT INTO `category` (`id`,`category_name`) VALUES (31510,'Laptop Power Adapters/Chargers');
INSERT INTO `category` (`id`,`category_name`) VALUES (3323,'Lenses');
INSERT INTO `category` (`id`,`category_name`) VALUES (19591,'Lighting Kits');
INSERT INTO `category` (`id`,`category_name`) VALUES (37915,'Locks, Latches & Keys');
INSERT INTO `category` (`id`,`category_name`) VALUES (96991,'Memory Cards');
INSERT INTO `category` (`id`,`category_name`) VALUES (4250,'Mens Accessories');
INSERT INTO `category` (`id`,`category_name`) VALUES (1059,'Mens Clothing');
INSERT INTO `category` (`id`,`category_name`) VALUES (93427,'Mens Shoes');
INSERT INTO `category` (`id`,`category_name`) VALUES (11233,'Music');
INSERT INTO `category` (`id`,`category_name`) VALUES (619,'Musical Instruments & Gear');
INSERT INTO `category` (`id`,`category_name`) VALUES (57989,'Pants');
INSERT INTO `category` (`id`,`category_name`) VALUES (177,'PC Laptops & Netbooks');
INSERT INTO `category` (`id`,`category_name`) VALUES (1281,'Pet Supplies');
INSERT INTO `category` (`id`,`category_name`) VALUES (167948,'Plumbing & Fixtures');
INSERT INTO `category` (`id`,`category_name`) VALUES (870,'Pottery & Glass');
INSERT INTO `category` (`id`,`category_name`) VALUES (1245,'Printers');
INSERT INTO `category` (`id`,`category_name`) VALUES (10542,'Real Estate');
INSERT INTO `category` (`id`,`category_name`) VALUES (176979,'Screen Protectors');
INSERT INTO `category` (`id`,`category_name`) VALUES (888,'Sporting Goods');
INSERT INTO `category` (`id`,`category_name`) VALUES (754,'Sports');
INSERT INTO `category` (`id`,`category_name`) VALUES (64482,'Sports Mem, Cards & Fan Shop');
INSERT INTO `category` (`id`,`category_name`) VALUES (15687,'T-Shirts');
INSERT INTO `category` (`id`,`category_name`) VALUES (171485,'Tablets & eBook Readers');
INSERT INTO `category` (`id`,`category_name`) VALUES (2228,'Textbooks, Education');
INSERT INTO `category` (`id`,`category_name`) VALUES (3252,'Travel');
INSERT INTO `category` (`id`,`category_name`) VALUES (30093,'Tripods & Monopods');
INSERT INTO `category` (`id`,`category_name`) VALUES (2624,'TV & Movie Character Toys');
INSERT INTO `category` (`id`,`category_name`) VALUES (75708,'TV, Movie & Video Games');
INSERT INTO `category` (`id`,`category_name`) VALUES (155184,'Unisex Clothing, Shoes & Accs');
INSERT INTO `category` (`id`,`category_name`) VALUES (51071,'USB Flash Drives');
INSERT INTO `category` (`id`,`category_name`) VALUES (1249,'Video Games & Consoles');
INSERT INTO `category` (`id`,`category_name`) VALUES (175759,'Vintage');
INSERT INTO `category` (`id`,`category_name`) VALUES (37918,'Weathervanes & Lightning Rods');
INSERT INTO `category` (`id`,`category_name`) VALUES (3259,'Wedding & Formal Occasion');
INSERT INTO `category` (`id`,`category_name`) VALUES (4251,'Womens Accessories');
INSERT INTO `category` (`id`,`category_name`) VALUES (15724,'Womens Clothing');
INSERT INTO `category` (`id`,`category_name`) VALUES (3034,'Womens Shoes');
INSERT INTO `category` (`id`,`category_name`) VALUES (155240,'World & Traditional Clothing');